name: uma_genai
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - et_xmlfile=2.0.0=py311hca03da5_0
  - expat=2.7.1=h313beb8_0
  - libcxx=17.0.6=he5c5206_4
  - libffi=3.4.4=hca03da5_1
  - ncurses=6.5=hee39554_0
  - openpyxl=3.1.5=py311h80987f9_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.1=pyhc872135_2
  - python=3.11.13=h19e8193_0
  - readline=8.3=h0b18652_0
  - setuptools=78.1.1=py311hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.14=h6ba3021_1
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
    - annotated-types==0.7.0
    - anyio==4.10.0
    - cachetools==5.5.2
    - certifi==2025.8.3
    - charset-normalizer==3.4.2
    - distro==1.9.0
    - google-auth==2.40.3
    - google-genai==1.29.0
    - h11==0.16.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - idna==3.10
    - jiter==0.12.0
    - numpy==2.3.2
    - openai==2.8.1
    - pandas==2.3.1
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pydantic==2.11.7
    - pydantic-core==2.33.2
    - pypdf==5.9.0
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - requests==2.32.4
    - rsa==4.9.1
    - six==1.17.0
    - sniffio==1.3.1
    - tenacity==9.1.2
    - tqdm==4.67.1
    - typing-extensions==4.14.1
    - typing-inspection==0.4.1
    - tzdata==2025.2
    - urllib3==2.5.0
    - websockets==15.0.1
    - xlsxwriter==3.2.5
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/uma_genai
